name: Deploy Docs

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  docs_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3

      - name: Install Doxygen
        run: sudo apt install -y doxygen

      - name: Generate docs
        run: doxygen docs/Doxyfile

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/html
